# Generated by Django 5.2.9 on 2026-01-10 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(db_index=True, max_length=500)),
                ('profile_url', models.URLField(unique=True)),
                ('headline_text', models.TextField(blank=True, null=True)),
                ('about_text', models.TextField(blank=True, null=True)),
                ('experience_text', models.TextField(blank=True, null=True)),
                ('skills_text', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-extracted_at'],
                'indexes': [models.Index(fields=['search_query', '-extracted_at'], name='linkedin_op_search__8ea3f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='OptimizationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfileSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline_text', models.TextField(blank=True, null=True)),
                ('about_text', models.TextField(blank=True, null=True)),
                ('experience_text', models.TextField(blank=True, null=True)),
                ('skills_text', models.TextField(blank=True, null=True)),
                ('raw_input_type', models.CharField(choices=[('manual', 'Manual Input'), ('oauth', 'LinkedIn OAuth')], max_length=20)),
                ('linkedin_profile_url', models.URLField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimized_headline', models.TextField()),
                ('optimized_about', models.TextField()),
                ('optimized_experience', models.JSONField()),
                ('recommended_skills', models.JSONField()),
                ('gap_analysis', models.JSONField(blank=True, null=True)),
                ('seo_score', models.FloatField(default=0.0)),
                ('keyword_relevance_score', models.FloatField(default=0.0)),
                ('profile_completeness_score', models.FloatField(default=0.0)),
                ('skill_match_score', models.FloatField(default=0.0)),
                ('structural_quality_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='linkedin_optimizer.optimizationjob')),
                ('profile_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_results', to='linkedin_optimizer.userprofilesnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='optimizationjob',
            name='profile_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_jobs', to='linkedin_optimizer.userprofilesnapshot'),
        ),
        migrations.CreateModel(
            name='OptimizationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=255)),
                ('target_location', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('experience_level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead/Principal')], max_length=20)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='linkedin_optimizer.userprofilesnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('role', 'Role Keyword'), ('skill', 'Skill Keyword'), ('industry', 'Industry Keyword'), ('soft_skill', 'Soft Skill'), ('action_verb', 'Action Verb')], max_length=20)),
                ('frequency', models.IntegerField(default=1)),
                ('importance_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('optimization_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='linkedin_optimizer.optimizationcontext')),
            ],
            options={
                'ordering': ['-importance_score', '-frequency'],
                'indexes': [models.Index(fields=['optimization_context', '-importance_score'], name='linkedin_op_optimiz_7d58a0_idx')],
                'unique_together': {('optimization_context', 'keyword', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ActionableChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_item', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('optimization_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='linkedin_optimizer.optimizationresult')),
            ],
            options={
                'ordering': ['order', '-priority'],
                'indexes': [models.Index(fields=['optimization_result', 'is_completed'], name='linkedin_op_optimiz_2ff1a9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='userprofilesnapshot',
            index=models.Index(fields=['user', '-created_at'], name='linkedin_op_user_id_5f8a67_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationresult',
            index=models.Index(fields=['profile_snapshot', '-created_at'], name='linkedin_op_profile_ce1ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationresult',
            index=models.Index(fields=['-seo_score'], name='linkedin_op_seo_sco_d2be4e_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationjob',
            index=models.Index(fields=['user', '-created_at'], name='linkedin_op_user_id_92ba17_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationjob',
            index=models.Index(fields=['celery_task_id'], name='linkedin_op_celery__cd3cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationcontext',
            index=models.Index(fields=['target_role', 'target_location'], name='linkedin_op_target__01bfdc_idx'),
        ),
    ]
