# Generated by Django 5.2.9 on 2026-01-25 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizationcontext',
            name='profile_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='linkedin_optimizer.userprofilesnapshot'),
        ),
    ]
