# Generated by Django 5.2.9 on 2026-01-18 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('sub_title', models.CharField(blank=True, max_length=150, null=True)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('ai_words_limit', models.PositiveBigIntegerField(default=0)),
                ('keywords_limit', models.PositiveIntegerField(default=0)),
                ('pages_limit', models.PositiveIntegerField(default=0)),
                ('project', models.PositiveIntegerField(default=0)),
                ('max_users', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('billing_type', models.CharField(choices=[('one_time', 'One Time'), ('subscription', 'Subscription')], default='subscription', max_length=20)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('other', 'Other')], max_length=20)),
                ('duration_days', models.PositiveBigIntegerField(blank=True, default=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_plan_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_plan_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('stripe_customer', models.CharField(blank=True, max_length=500, null=True)),
                ('stripe_checkout_id', models.CharField(blank=True, max_length=500, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=500, null=True)),
                ('mode', models.CharField(blank=True, choices=[('setup', 'setup'), ('one_time', 'one_time'), ('subscription', 'Subscription')], max_length=50, null=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=500, null=True)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=500, null=True)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4)),
                ('quantity', models.IntegerField(default=1)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.priceplan')),
            ],
        ),
    ]
