# Generated by Django 5.1.7 on 2025-06-11 08:09

from django.db import migrations
from django.core.management import call_command

def load_user_roles(apps, schema_editor):
    call_command('loaddata', 'users/fixtures/role.json')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=load_user_roles,
            reverse_code=migrations.RunPython.noop
        ),
    ]



