# Generated by Django 5.1.7 on 2025-06-14 14:34

import os
import json
from django.db import migrations
from django.conf import settings

from django.core.management import call_command

def load_admin_and_its_profile(apps, schema_editor):
    call_command('loaddata', 'users/fixtures/users.json')
    # call_command('loaddata', 'users/fixtures/users_profile.json')

     # Get model dynamically to avoid direct import issues
    UserProfile = apps.get_model('users', 'UserProfile')

    # Load fixture file manually
    fixture_path = os.path.join(settings.BASE_DIR, 'users', 'fixtures', 'users_profile.json')
    with open(fixture_path, 'r') as f:
        raw_data = json.load(f)

    # Get model fields to check which ones are relational
    model_fields = {field.name: field for field in UserProfile._meta.get_fields()}

    for record in raw_data:
        fields_data = record["fields"]  # The actual model data in a Django fixture

        cleaned_data = {}

        for key, value in fields_data.items():
            field = model_fields.get(key)

            if field is None:
                # Skip if the field doesn't exist in the model
                continue

            # If the field is a ForeignKey or OneToOneField
            if field.is_relation and (field.many_to_one or field.one_to_one):
                cleaned_data[f"{key}_id"] = value
            else:
                cleaned_data[key] = value

        # Finally create the record
        UserProfile.objects.create(**cleaned_data)



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_data_migration'),
    ]

    operations = [
        migrations.RunPython(
            code=load_admin_and_its_profile,
            reverse_code=migrations.RunPython.noop
        ),
    ]
