# Generated by Django 5.1.7 on 2025-10-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_auth_provider_userprofile_google_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='users_userp_role_id_d674f4_idx'),
        ),
    ]
