# Generated by Django 5.2.9 on 2026-01-18 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '__first__'),
        ('users', '0006_userprofile_contact_userprofile_hear_about_us_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_obj', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credits', models.PositiveIntegerField(default=0)),
                ('total_ai_words_limit', models.PositiveBigIntegerField(default=0)),
                ('total_keywords_limit', models.PositiveIntegerField(default=0)),
                ('total_pages_limit', models.PositiveIntegerField(default=0)),
                ('total_projects', models.PositiveBigIntegerField(default=0)),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('ai_words_used', models.PositiveBigIntegerField(default=0)),
                ('keywords_used', models.PositiveIntegerField(default=0)),
                ('pages_used', models.PositiveIntegerField(default=0)),
                ('projects_created', models.PositiveIntegerField(default=0)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=200, null=True)),
                ('subscription_start', models.DateField(blank=True, null=True)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('is_renewal', models.BooleanField(default=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.priceplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
